// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

import java.util.NoSuchElementException;

/************************************************************/
/**
 * Diese Klasse beinhaltet generelle Daten, über den Zustand der Software.
 */
public class GeneralData extends ElipseModel {

    /**
     * Das momentane Semester.
     */
    private Semester currentSemester;

    /**
     * Getter für das aktuelle Semester.
     * 
     * @return Das aktuelle Semester.
     */
    public Semester getCurrentSemester() {
        return currentSemester;
    }

    /**
     * Setter für das aktuelle Semester.
     * 
     * @param currentSemester
     *            Das aktuelle Semester.
     */
    public void setCurrentSemester(Semester currentSemester) {
        this.currentSemester = currentSemester;
    }

    /**
     * Lädt die Daten aus der Datenbank
     */
    public static GeneralData getInstance() {
        try {
            return ElipseModel.getAll(GeneralData.class).stream().findFirst().get();
        } catch (NoSuchElementException e) {
            GeneralData data = new GeneralData();
            data.save();
            return data;
        }

    }

}
