// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

import exception.DataException;

/************************************************************/
/**
 * Klasse, die ein Project repräsentiert
 */
@Entity
public class Project extends ElipseModel implements Comparable<Project> {

    /**
     * Der Name des Projektes.
     */
    @NotNull
    private String        name;
    /**
     * Die minimale Anzahl der Teilnehmer einer Gruppe für dieses Projekt.
     */
    private int           minTeamSize;
    /**
     * Die maximale Anzahl der Teilnehmer einer Gruppe für dieses Projekt.
     */
    private int           maxTeamSize;
    /**
     * Anzahl der Teams die zu diesem Projekt zugeteilt werden.
     */
    private int           numberOfTeams;
    /**
     * Die Projektbeschreibung.
     */
    @NotNull
    private String        projectInfo;
    /**
     * URL zu der Website des Projektes.
     */
    @NotNull
    private String        projectURL;
    /**
     * Das Institut, welches das Projekt anbietet.
     */
    @NotNull
    private String        institute;
    /**
     * Betreuer des Projekts
     */
    @ManyToMany
    private List<Adviser> advisers;

    /**
     * Danke Ebean.
     */
    @ManyToOne
    private Semester      semester;

    public Project() throws DataException {
        this("default_name", "default_info", "default_institut", "default_url");
    }

    public Project(String name, String projectInfo, String institut, String url)
            throws DataException {
        super();
        setName(name);
        setProjectInfo(projectInfo);
        setInstitute(institut);
        setProjectURL(url);
        advisers = new ArrayList<>();
    }

    // TODO Was ist das für 1 Konstruktor?
    public Project(String name, Adviser adviser) throws DataException {
        this();
        setName(name);
        advisers.add(adviser);
    }

    /**
     * Setter für das Semester. Sollte nicht manuell benutzt werden. Zum Setzten
     * reicht es, das Projekt uber Semester.addProject() oder
     * Semester.setProjects hinzuzufügen.
     * 
     * @param semester
     *            Das Semester, zu dem diese Projekt gehört.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setSemester(Semester semester) throws DataException {
        if (semester == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        this.semester = semester;
    }

    /**
     * Getter für die Anzahl der Teams.
     * 
     * @return Anzahl der Teams.
     */
    public int getNumberOfTeams() {
        return numberOfTeams;
    }

    /**
     * Setter für die Anzahl der Teams.
     * 
     * @param numberOfTeams
     *            Anzahl der Teams.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setNumberOfTeams(int numberOfTeams) throws DataException {
        if (numberOfTeams < 1) {
            throw new DataException("project.invalidTeamNumber");
        } else {
            this.numberOfTeams = numberOfTeams;
        }
    }

    /**
     * Getter für die Betreuer des Projekts.
     * 
     * @return Betreuer des Projekts.
     */
    public List<Adviser> getAdvisers() {
        return advisers;
    }

    /**
     * Setter für die Betreuer des Projekts.
     * 
     * @param advisers
     *            Betreuer des Projekts.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setAdvisers(List<Adviser> advisers) throws DataException {
        if (advisers == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        if (advisers.isEmpty()) {
            throw new DataException(LIST_EMPTY_ERROR);
        }
        this.advisers = advisers;
    }

    /**
     * Fügt dem Projekt einen Betreuer hinzu.
     * 
     * @param adviser
     *            Betreuer der hinzugefügt wird.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void addAdviser(Adviser adviser) throws DataException {
        if (adviser == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        advisers.add(adviser);
    }

    /**
     * Entfernt einen Betreuer vom Projekt.
     * 
     * @param adviser
     *            Betreuer der entfernt wird.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void removeAdviser(Adviser adviser) throws DataException {
        if (adviser == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        advisers.remove(adviser);
    }

    /**
     * Getter für den Namen des Projektes.
     * 
     * @return Der Name des Projektes.
     */
    public String getName() {
        return name;
    }

    /**
     * Getter der maximalen Größe für Teams dieses Projektes. -1 entspricht
     * keiner gesetzten Teamgröße.
     * 
     * @return Die maximale Teamgröße.
     */
    public int getMaxTeamSize() {
        return maxTeamSize;
    }

    /**
     * Getter der minimalen Größe für Teams dieses Projektes. -1 entspricht
     * keiner gesetzten Teamgröße.
     * 
     * @return Die minimale Teamgröße.
     */
    public int getMinTeamSize() {
        return minTeamSize;
    }

    /**
     * Getter für die Information über dieses Projektes.
     * 
     * @return Die Information des Projektes.
     */
    public String getProjectInfo() {
        return projectInfo;
    }

    /**
     * Getter für die URL des Projektes.
     * 
     * @return Die URL des Projektes.
     */
    public String getProjectURL() {
        return projectURL;
    }

    /**
     * Setter für den Namen des Projektes.
     * 
     * @param name
     *            Der Name des Projektes.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setName(String name) throws DataException {
        if (name == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        if (name.isEmpty()) {
            throw new DataException(STRING_EMPTY_ERROR);
        }
        this.name = name;
    }

    /**
     * Setter der maximalen Größe für Teams dieses Projektes. -1 entspricht
     * keiner gesetzten Teamgröße.
     * 
     * @param maxTeamSize
     *            Die maximale Größe für Teams dieses Projektes.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setMaxTeamSize(int maxTeamSize) throws DataException {
        if (maxTeamSize < 0) {
            throw new DataException("project.invalidTeamSize");
        }
        this.maxTeamSize = maxTeamSize;

    }

    // TODO Wo wird geprüft, ob max > min ist?
    /**
     * Setter der minimalen Größe für Teams dieses Projektes. -1 entspricht
     * keiner gesetzten Teamgröße.
     * 
     * @param minTeamSize
     *            Die minimale Größe für Teams dieses Projektes.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setMinTeamSize(int minTeamSize) throws DataException {
        if (minTeamSize < 0) {
            throw new DataException("project.invalidTeamSize");
        }
        this.minTeamSize = minTeamSize;
    }

    /**
     * Setter für die Information über dieses Projektes.
     * 
     * @param projektInfo
     *            Die Information des Projektes.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setProjectInfo(String projectInfo) throws DataException {
        if (projectInfo == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        if (projectInfo.isEmpty()) {
            throw new DataException(STRING_EMPTY_ERROR);
        }
        this.projectInfo = projectInfo;
    }

    /**
     * Setter für die URL des Projektes.
     * 
     * @param projectURL
     *            Die URL des Projektes.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setProjectURL(String projectURL) throws DataException {
        if (projectURL == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        if (projectURL.isEmpty()) {
            throw new DataException(STRING_EMPTY_ERROR);
        }
        // TODO Sollen wir sogar mit NetURL auf ne echte Website prüfen?
        // Falls ja, muss der Standardkonstruktor angepasst werden
        this.projectURL = projectURL;
    }

    /**
     * Gibt den Institutsnamen des Institutes zurück, welches das Projekt
     * anbietet.
     * 
     * @return den Namen
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * Setzt den Institutsnamen.
     * 
     * @param institute
     *            der Name des Instituts.
     * @throws DataException
     *             Wird vom Controller behandelt.
     */
    public void setInstitute(String institute) throws DataException {
        if (institute == null) {
            throw new DataException(IS_NULL_ERROR);
        }
        if (institute.isEmpty()) {
            throw new DataException(STRING_EMPTY_ERROR);
        }
        this.institute = institute;
    }

    /**
     * Diese Methode gibt alle Projekte zurück.
     * 
     * @return Alle Projekte.
     */
    public static List<Project> getProjects() {
        return ElipseModel.getAll(Project.class);
    }

    /**
     * Gibt das Semester zurück, in dem das Projekt angeboten wurde.
     * 
     * @return Semester, in dem das Projekt angeboten wurde.
     */
    public Semester getSemester() {
        return semester;
    }

    @Override
    public int compareTo(Project o) {
        return name.compareTo(o.getName());
    }

}
