// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

import com.avaje.ebean.event.ServerConfigStartup;

/**
 * Klasse, die die Datenbank initialisiert.
 */
public class PSEServerConfigStartup implements ServerConfigStartup {

    /**
     * Initialisiert die Datenbank.
     *
     * @param serverConfig
     *            Ein Objekt, welches zur Konfiguration des Servers verwendet
     *            wird.
     */
    @Override
    public void onStart(com.avaje.ebean.config.ServerConfig serverConfig) {
        serverConfig.setDefaultServer(true);
    }
}
