// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/************************************************************/
/**
 * Diese Klasse stellt eine Bewertung eines Studierenden oder einer Lerngruppe
 * für ein Projekt dar.
 */
@Entity
public class Rating extends ElipseModel {

    public static final int MINIMAL_RATING = 1;
    public static final int MAXIMAL_RATING = 5;

    /**
     * Der Wert der Bewertung.
     */
    @Min(1)
    @Max(5)
    private int             rating;
    /**
     * Das Projekt, dem die Bewertung gilt.
     */
    @ManyToOne
    @NotNull
    private Project         project;

    // Ebean braucht das hier
    @ManyToOne
    private LearningGroup   learningGroup;

    public Rating() {
        this(1, new Project(Project.DEFAULT_NAME, Project.DEFAULT_INFO,
                Project.DEFAULT_INSTITUTE, Project.DEFAULT_URL));
    }

    public Rating(int rating, Project project) {
        super();
        this.rating = rating;
        this.project = project;
    }

    public LearningGroup getLearningGroup() {
        return learningGroup;
    }

    /**
     * Setter für die Lerngruppe. Sollte nicht manuell benutzt werden. Zum
     * Setzten reicht es, die Lerngruppe uber LearningGroup.rate() oder
     * LearningGroup.setRatings() hinzuzufügen.
     * 
     * @param learningGroup
     *            Die Lerngruppe, zu dem diese Bewertung gehört.
     */
    public void setLearningGroup(LearningGroup learningGroup) {
        this.learningGroup = learningGroup;
    }

    /**
     * Getter für den Wert der Bewertung.
     * 
     * @return Der Wert der Bewertung.
     */
    public int getRating() {
        return rating;
    }

    /**
     * Getter für das Projekt der Bewertung.
     * 
     * @return Das Projekt, das bewertet wird.
     */
    public Project getProject() {
        return project;
    }

    /**
     * Setter für den Wert der Bewertung.
     * 
     * @param rating
     *            Der Wert der Bewertung.
     */
    public void setRating(int rating) {
        this.rating = rating;
    }

    /**
     * Setter für das Projekt der Bewertung.
     * 
     * @param project
     *            Das Projekt, das bewertet wird.
     */
    public void setProject(Project project) {
        this.project = project;
    }

}
