// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package allocation;

import exception.AllocationException;
import gurobi.GRBLinExpr;

/************************************************************/
/**
 * Das Kriterium sorgt dafür, dass Studierende, die sich schon einmal für einen
 * PSE Platz beworben haben, bevorzugt werden.
 */
public class CriterionRegisteredAgain implements GurobiCriterion {
    private String name;

    /**
     * Standard-Konstruktor, der den Namen eindeutig setzt
     */
    public CriterionRegisteredAgain() {
        this.name = "RegisteredAgain";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * {@inheritDoc}
     */
	@Override
	public void useCriteria(Configuration configuration, GurobiAllocator allocator, double weight)
			throws AllocationException {
		GRBLinExpr bonus = new GRBLinExpr();
		for (int i = 0; i < configuration.getStudents().size(); i++) {
			// TODO if (configuration.getStudents().get(i).)
		}
		
	}
}