// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Semester;

/************************************************************/
/**
 * Diese Klasse beinhaltet generelle Daten, über den Zustand der Software.
 */
public class GeneralData {
	/**
	 * Das momentane Semester.
	 */
	private Semester currentSemester;
	/**
	 * Anmeldename des Admind.
	 */
	private static String adminName;
	/**
	 * Anmeldepasswort des Admins.
	 */
	private static String adminPassword;
	
	public Semester getCurrentSemester() {
	    return currentSemester;
	}
	
	public String getAdminName() {
	    return this.adminName;
	}
	
	public String getAdminPassword() {
	    return this.adminPassword;
	}
};
