// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Semester;

/************************************************************/
/**
 * Diese Klasse repräsentiert eine Lerngruppe, das heißt eine Gruppe von Studierenden,
 * die sich gemeinsam zum PSE anmelden wollen.
 */
public class LearningGroup {
	/**
	 * Der name der LErngruppe.
	 */
	private String name;
	/**
	 * Das nötige Passwort, um der Lerngruppe beizutreten.
	 */
	private String password;
	/**
	 * Das Semster, in dem die Lerngruppe erstellt wurde.
	 */
	private Semester semester;
	/**
	 * Die Mitglieder der Lerngruppe.
	 */
	private Student[] members;
	
	/**
	 * Getter für den Namen.
	 * @return Name der Lerngruppe.
	 */
	public String getName() {
	    return name;
	}
	/**
	 * Getter für das Passwort.
	 * @return Das Passwort, um der Lerngruppe beizutreten.
	 */
	public String getPassword() {
	    return password;
	}
	/**
	 * Getter für das Semester, in dem die Lerngruppe erstellt wurde.
	 * @return Das Semester,in dem die Lerngruppe erstellt wurde.
	 */
	public Semester getSemester() {
	    return Semester;
	}
	/**
	 * Getter für die Mitglieder der Lerngruppe.
	 * @return Die Mitglieder der Lerngruppe.
	 */
	public Student[] getMembers() {
	    return members;
	}
	/**
	 * Studierende, die keiner Lerngruppe angehören, werden als private Lerngruppe der
	 * Größe 1 gespeichert. Eine private Lerngruppe kann also niemals von einem Studenten erstellt werden.
	 */
	public boolean isPrivate;
	
	/**
	 * Diese Methode gibt eine spezifische Lerngruppe zurück.
	 * @param name Der Name der Lerngruppe.
	 * @param semester Das Semster, in dem die Lerngruppe erstellt wurde.
	 * @return learningGroup Die spezifische Lerngruppe.
	 */
	public static RootElement.data.LearningGroup getLearningGroup(String name, Semester semester) {
	}

	/**
	 * Diese Methode gibt alle jemals erstellten Lerngruppen zurück.
	 * @return learningGroups Alle LErngruppen.
	 */
	public static RootElement.data.LearningGroup getLearningGroups() {
	}
};
