// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Semester;

/************************************************************/
/**
 * Diese Klasse reprüsentiert eine Lerngruppe, das heiüt eine Gruppe von Studierenden,
 * die sich gemeinsam zum PSE anmelden wollen.
 */
public class LearningGroup {
	/**
	 * Der name der Lerngruppe.
	 */
	private String name;
	/**
	 * Das nütige Passwort, um der Lerngruppe beizutreten.
	 */
	private String password;
	/**
	 * Das Semster, in dem die Lerngruppe erstellt wurde.
	 */
	private Semester semester;
	/**
	 * Die Mitglieder der Lerngruppe.
	 */
	private Student[] members;
	
	/**
     * Studierende, die keiner Lerngruppe angehüren, werden als private Lerngruppe der
     * Grüüe 1 gespeichert. Eine private Lerngruppe kann also niemals von einem Studenten erstellt werden.
     */
    private boolean isPrivate;
	
	/**
	 * Getter für den Namen.
	 * @return Name der Lerngruppe.
	 */
	public String getName() {
	    return name;
	}
	/**
	 * Getter für das Passwort.
	 * @return Das Passwort, um der Lerngruppe beizutreten.
	 */
	public String getPassword() {
	    return password;
	}
	/**
	 * Getter für das Semester, in dem die Lerngruppe erstellt wurde.
	 * @return Das Semester,in dem die Lerngruppe erstellt wurde.
	 */
	public Semester getSemester() {
	    return Semester;
	}
	/**
	 * Getter für die Mitglieder der Lerngruppe.
	 * @return Die Mitglieder der Lerngruppe.
	 */
	public Student[] getMembers() {
	    return members;
	}
	
	public boolean isPrivate() {
	    return this.isPrivate;
	}
	
	/**
     * Setter für den Namen.
     * @param name Name der Lerngruppe.
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Setter für das Passwort.
     * @param password Das Passwort, um der Lerngruppe beizutreten.
     */
    public void setPassword(String password) {
        this.password = password;
    }
    /**
     * Setter für das Semester, in dem die Lerngruppe erstellt wurde.
     * @param semester Das Semester,in dem die Lerngruppe erstellt wurde.
     */
    public void setSemester(Semester semseter) {
        this.semester = semester;
    }
    /**
     * Setter für die Mitglieder der Lerngruppe.
     * @param members Die Mitglieder der Lerngruppe.
     */
    public void setMembers(Student[] members) {
        this.members = members;
    }
    /**
     * Getter ob Lerngruppe privat ist.
     * @return Wahr, wenn privat, sonst falsch.
     */
    public boolean isPrivate() {
        return this.isPrivate;
    }
    /**
     * Setter ob Lerngruppe privat ist.
     * @param isPrivate Wahr, wenn privat, sonst falsch.
     */
    public boolean setPrivate(boolean isPrivate) {
        this.isPrivate = isPrivate;
    }
	
	/**
	 * Diese Methode gibt eine spezifische Lerngruppe zurück.
	 * @param name Der Name der Lerngruppe.
	 * @param semester Das Semster, in dem die Lerngruppe erstellt wurde.
	 * @return learningGroup Die spezifische Lerngruppe.
	 */
	public static RootElement.data.LearningGroup getLearningGroup(String name, Semester semester) {
	}

	/**
	 * Diese Methode gibt alle jemals erstellten Lerngruppen zurück.
	 * @return learningGroups Alle LErngruppen.
	 */
	public static RootElement.data.LearningGroup getLearningGroups() {
	}
};
