// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Rating;
import RootElement.data.Semester;
import RootElement.data.Student;

/************************************************************/
/**
 * 
 */
public class Project {
	/**
	 * Der Name des Projektes.
	 */
	private String name;
	/**
	 * Die minimale Anzahl der Teilnehmer einer Gruppe für dieses Projekt.
	 */
	private int minTeamSize;
	/**
	 * Die maximale Anzahl der Teilnehmer einer Gruppe für dieses Projekt.
	 */
	private int maxTeamSize;
	/**
	 * Die Projektbeschreibung.
	 */
	private String projectInfo;
	/**
	 * URL zu der Website des Projektes.
	 */
	private String projectURL;
	/**
	 * Teams des Projekt
	 */
	private Team[] teams;
	/**
	 * Getter für den Namen des Projektes.
	 * @return Der Name des Projektes.
	 */
	public String getName() {
	    return name;
	}
	/**
	 * Getter der maximalen Grüüe für Teams dieses Projektes.
	 * @return Die maximale Teamgrüüe.
	 */
	public int getMaxTeamSize() {
	    return this.maxTeamSize;
	}
	/**
     * Getter der minimalen Grüüe für Teams dieses Projektes.
     * @return Die minimale Teamgrüüe.
     */
    public int getMinTeamSize() {
        return this.minTeamSize;
    }
    /**
     * Getter für die Information über dieses Projektes.
     * @return Die Information des Projektes.
     */
    public String getProjectInfo() {
        return this.projectInfo;
    }
    /**
     * Getter für die URL des Projektes.
     * @return Die URL des Projektes.
     */
    public String getProjectURL() {
        return this.projectURL;
    }
    /**
     * Getter für die Teams des Projektes.
     * @return Die Teams des Projektes.
     */
    public Team[] getTeams() {
        return this.teams;
    }
	/**
	 * Diese Methode gibt alle Projekte zurück.
	 * @return projects Alle Projekte.
	 */
	public static RootElement.data.Project getProjects() {
	}

	/**
	 * Diese Methode gibt ein spezifisches Projekt zurück, welches über seinen Namen und
	 * das Semester, in dem es erstellt wurde, identifiziert wird.
	 * @param name Der Name des Projektes.
	 * @param semester Das Semester, in dem das Projekt erstellt wurde.
	 * @return project Das spezifiscche Projekt.
	 */
	public static RootElement.data.Project getProject(String name, Semester semester) {
	}

	/**
	 * Diese Methode gibt die Bewertung eines spezifischen Studenten für dieses Projekt zurück.
	 * @param student Der Student, dessen Bewertung zurückgegeben werdedn soll.
	 * @return rating Die Bewertung des Studenten.
	 */
	public Rating getRating(Student student) {
	}
};
