// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Rating;
import RootElement.data.Semester;
import RootElement.data.Student;

/************************************************************/
/**
 * 
 */
public class Project {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public int minTeamSize;
	/**
	 * 
	 */
	public int maxTeamSize;
	/**
	 * 
	 */
	public String projectInfo;
	/**
	 * 
	 */
	public String projectURL;

	/**
	 * 
	 * @return projects 
	 */
	public static RootElement.data.Project getProjects() {
	}

	/**
	 * 
	 * @param name 
	 * @param semester 
	 * @return project 
	 */
	public static RootElement.data.Project getProject(String name, Semester semester) {
	}

	/**
	 * 
	 * @param student 
	 * @return rating 
	 */
	public Rating getRating(Student student) {
	}
};
