// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Adviser;
import RootElement.data.Allocation;
import RootElement.data.SPO;
import RootElement.data.Team;

/************************************************************/
/**
 * This class represents a semester in the data model.
 */
public class Semester {
	/**
	 * The semester's name in format: *******
	 */
	public String name;
	/**
	 * The available SPOs for this semster.
	 */
	public SPO[] spos;
	/**
	 * A description for the students.
	 */
	public String infoText;
	/**
	 * The final allocation for this semster.
	 */
	public Allocation finalAllocation;

	/**
	 * This method returns a specific semester by a given name.
	 * @param semesterName The name of the semester.
	 * @return semester The searched semester.
	 */
	public static RootElement.data.Semester getSemester(String semesterName) {
	}

	/**
	 * This class returns all semesters ever created.
	 * @return semesters All semseters ever created.
	 */
	public static RootElement.data.Semester getSemesters() {
	}

	/**
	 * This method returns all existing teams of this semester.
	 * @return teams All existing teams.
	 */
	public Team getTeams() {
	}

	/**
	 * This method returns all existing advisors of this semster.
	 * @return advisers All existing advisors
	 */
	public Adviser getAdvisers() {
	}
};
