// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Achievement;

/************************************************************/
/**
 * Diese Klasse stellt eine Studienprüfungsordnung dar.
 */
public class SPO {
	/**
	 * Der Name der Prüfungsordnung.
	 */
	private String name;
	/**
	 * Die nach dieser Prüfungsordnung benütigten Teilleistungen für die Teilnahme am PSE.
	 */
	private Achievement[] necessaryAchievements;
	/**
	 * Die zum Einstellen verfügbaren Teilleistungen.
	 */
	private Achievement[] avaliableAchievements;
	/**
	 * Getter-Methode für name.
	 * @return Der Name der SPO.
	 */
	public String getName() {
	    return name;
	}
	/**
     * Getter-Methode für die benütigten Teilleistungen.
     * @return Die benütigten Teilleistungen.
     */
	public Achievement[] getNecessaryAchievements() {
	    return necessaryAchievements;
	}
	/**
     * Getter-Methode für die verfügbaren Teilleistungen.
     * @return Die verfügbaren Teilleistungen.
     */
	public Achievement[] getAvailableAchievements() {
        return availableAchievements;
    }
	/**
     * Setter-Methode f�r name.
     * @param name Der Name der SPO.
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Setter-Methode f�r die ben�tigten Teilleistungen.
     * @param neccessaryAchievemens Die ben�tigten Teilleistungen.
     */
    public void setNecessaryAchievements(Achievement[] neccessaryAchievements) {
        this.necessaryAchievements = necessaryachievements;
    }
    /**
     * Setter-Methode f�r die verf�gbaren Teilleistungen.
     * @param availableAchievements Die verf�gbaren Teilleistungen.
     */
    public void setAvailableAchievements(Achievement[] availableAchievements) {
        this.avaliableAchievements = availableAchievements;
    }	
	/**
	 * Diese Methode gibt alle SPOs zurück.
	 * @return spos Alle SPOs.
	 */
	public static RootElement.data.SPO getSPOs() {
	}

	/**
	 * Dies Methode gibt eine bestimmte SPO zurück, die über ihren Namen identifiziert wird.
	 * @param name Der Name der SPO.
	 * @return spo Die SPO
	 */
	public static RootElement.data.SPO getSPO(String name) {
	}
};
