// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Achievement;

/************************************************************/
/**
 * 
 */
public class SPO {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public Achievement[] necessaryAchievements;
	/**
	 * 
	 */
	public Achievement[] avaliableAchievements;

	/**
	 * 
	 * @return spos 
	 */
	public static RootElement.data.SPO getSPOs() {
	}

	/**
	 * 
	 * @param name 
	 * @return spo 
	 */
	public static RootElement.data.SPO getSPO(String name) {
	}
};
