// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Achievement;
import RootElement.data.LearningGroup;
import RootElement.data.Project;
import RootElement.data.Rating;
import RootElement.data.SPO;
import RootElement.data.Semester;
import RootElement.data.Team;
import RootElement.data.User;

/************************************************************/
/**
 * Diese Klasse stellt einen Studierenden dar, der am PSE teilnimmt.
 **/
public class Student extends User {
	/**
	 * Die Matrikelnummer des Studierenden.
	 */
	private int matriculationNumber;
	/**
	 * Das Semester, in dem er sich zum ersten Mal registriert hat. 
	 */
	private Semester[] registeredSemesters;
	/**
	 * Die SPO des Studierenden
     */
	private SPO spo;
	/**
	 * Die Lerngruppen des Studierenden.
	 */
	private List<LearningGroup> learningGroups;
	/**
	 * Die bestandenen Teilleistungen.
	 */
	private Achievement[] completedAchievements;
	/**
	 * Wahr, wenn sich der Studierende bereits im campus management system f�r das PSE angemeldet hat.
	 * Falsch, sonst.
	 */
	private boolean registeredPSE;
	/**
	 * Wahr, wenn sich der Studierende bereits im campus management system f�r das TSE angemeldet hat.
     * Falsch, sonst.
	 */
	private boolean registeredTSE;
	/**
	 * Die PSE-Note des Studierenden.
	 */
	private int gradePSE;
	/**
	 * Die TSE-Note des Studierenden.
	 */
	private int gradeTSE;
	/**
	 * Die noch ausstehenden Teilleistungen des Studierenden.
	 */
	private Achievement[] oralTestAchievment;
	/**
	 * Das Semster der Erstregistrierung.
	 */
	private Semester startSemester;
	/**
	 * Das Semester, in dem sich der Studierende zum Zeitpunkt der Registrierung befindet.
	 */
	private int semesterAtRegistration;
	/**
	 * Getter f�r die Matrikelnummer.
	 * @return Die Matrikelnummer.
	 */
	public int getMatriculationNumber() {
	    return this.matriculationNumber;
	}
	/**
     * Getter f�r die Semester, in denen der Studierende registriert ist.
     * @return Die Semester, in denen der Studierende registriert ist.
     */
	public Semester[] getRegisteredSemesters() {
	    return this.registeredSemesters;
	}
	/**
	 * Getter f�r die SPO des Studierenden.
	 * @return Die SPO des Studierenden.
	 */
	public SPO getSPO() {
	    return this.spo;
	}
	/**
     * Getter f�r die Lerngruppen des Studierenden.
     * @return Die Lerngruppen des Studierenden.
     */
	public LearningGroup[] getLearningGroups() {
	    return this.learningGroups;
	}
	/**
     * Getter f�r die abgeschlossenen Teilleistungen des Studierenden.
     * @return Die abgeschlossenen Teilleistungen des Studierenden.
     */
	public Achievement[] getCompletedAchievements() {
	    return this.completedAchievements;
	}
	/**
     * Getter f�r die Variable, ob der Studierende im campus management system f�r das PSE angemeldet ist.
     * @return Wahr, wenn er angemeldet ist, falsch sonst.
     */
	public boolean isRegisteredPSE() {
	    return this.registeredPSE;
	}
	/**
     * Getter f�r die Variable, ob der Studierende im campus management system f�r das TSE angemeldet ist.
     * @return Wahr, wenn er angemeldet ist, falsch sonst.
     */
	public boolean isRegisteredTSE() {
	    return this.registeredTSE;
	}
	/**
     * Getter f�r die PSE-Note des Studierenden.
     * @return Die Note des Studierenden f�rs PSE.
     */
	public int getGradePSE() {
	    return this.gradePSE;
	}
	/**
     * Getter f�r die TSE-Note des Studierenden.
     * @return Die Note des Studierenden f�rs TSE.
     */
	public int getGradeTSE() {
	    return this.gradeTSE;
	}
	/**
     * Getter f�r die noch ausstehenden Teilleistungen des Studierenden.
     * @return Die noch ausstehenden Teilleistungen des Studierenden.
     */
	public Achievement[] getOralTestAchievement() {
	    return this.oralTestAchievment;
	}
	/**
     * Getter f�r das Semester des Studierenden.
     * @return Die noch ausstehenden Teilleistungen des Studierenden.
     */
	public Semester getSemester() {
	    return this.semesterAtRegistration;
	}
	
	public 
	/**
	 * Diese Methode gibt einen spezifischen Studierenden zur�ck, der durch seine Matrikelnummer
	 * identifiziert wird.
	 * @param matriculationNumber Die Matrikelnummer des Studierenden.
	 * @return student Der Studierende.
	 */
	public static RootElement.data.Student getStudent(int matriculationNumber) {
	}

	/**
	 * Diese Methode gibt alle Studierenden zur�ck.
	 * @return students Alle Studierende.
	 */
	public static RootElement.data.Student getStudents() {
	}

	/**
	 * Diese Methode gibt die Lerngruppe des Studierenden zur�ck.
	 * @return learningGroup Die Lerngruppe des Studierenden.
	 */
	public LearningGroup getCurrentLearningGroup() {
	}

	/**
	 * Diese Methode weist dem Studierenden eine neue Lerngruppe zu.
	 * @param learningGroup Die neue Lerngruppe des Studierenden.
	 */
	public void setCurrentLearningGroup(LearningGroup learningGroup) {
	}

	/**
	 * Diese Methode gibt die Bewertung des Studiereden zu einem bestimmten Projekt zur�ck.
	 * @param project Das Projekt.
	 * @return rating Die Bewertung des Studierenden f�r das bestimmte Projekt.
	 */
	public Rating getCurrentRating(Project project) {
	}

	/**
	 * Diese Methode setzt eine Bewertung des Studierenden f�r ein bestimmtes Projekt.
	 * @param project Das zu bewertende Projekt.
	 * @param rating Die Bewertung des Studierenden.
	 */
	public void setCurrentRating(Project project, Rating rating) {
	}

	/**
	 * Diese Methode gibt das Projekt zur�ck, dem der Studierende zugeteilt ist.
	 * @return project Das Projekt des Studeirenden.
	 */
	public Project getCurrentProject() {
	}

	/**
	 * Diese Methode gibt das Team, in dem der Studierende sich befindet, zur�ck.
	 * @return team Das Team des Studierenden.
	 */
	public Team getCurrentTeam() {
	}

	/**
	 * Diese Methode gibt das aktuelle Semester des Studierenden zur�ck.
	 * @return semester Das Semester, in dem Studierende sich aktuell befindet.
	 */
	public int getCurrentSemester() {
	}
};
