// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

import RootElement.data.Adviser;
import RootElement.data.Project;
import RootElement.data.Rating;
import RootElement.data.Student;

/************************************************************/
/**
 * Diese KLasse stellt ein Team eines Projektes dar.
 */
public class Team {
    
	/**
	 * Das Porjekt des Teams
	 */
	private Project project;
	/**
	 * Getter für das Projekt.
	 * @return Das Projekt.
	 */
	public Project getProject() {
	    return project;
	}
	/**
	 * Diese Methode gibt die Studierenden(Mitgliederr) des Teams zurück.
	 * @return members Die Mitglieder des Teams.
	 */
	public Student getMembers() {
	}

	/**
	 * Diese Methode gibt die Bewertung eines Studierenden zu dem Projekt dieses Teams zurück.
	 * @param student Der Studierende, dessen Bewertung zurückgegeben werden soll.
	 * @return rating Die Bewertung des Studierenden.
	 */
	public Rating getRating(Student student) {
	}

	/**
	 * Diese Methode gibt die Betreuer des Teams zurück.
	 * @return advisers Die Betreuer des Teams.
	 */
	public Adviser getAdvisers() {
	}
};
