// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.data;

/************************************************************/
/**
 * Diese Klasse stellt einen Benutzer der Anwendung dar.
 */
public class User {
	/**
	 * Der Anmeldename des Benutzers.
	 */
	private String username;
	/**
	 * Das Anmeldepasswort des Benutzers.
	 */
	private String password;
	/**
	 * Die Email-Adresse des Benutzers.
	 */
	private String emailAddress;
	/**
	 * Vorname des Benutzers.
	 */
	private String firstName;
	/**
	 * Nachname des Benutzers.
	 */
	private String lastName;
	/**
	 * Getter für den Benutzernamen.
	 * @return Der Benutzername.
	 */
	public String getUserName() {
	    return username;
	}
	/**
	 * Getter für das Benutzerpasswort.
	 * @return Das Benutzerpasswort.
	 */
	public String getPassword() {
	    return password;
	}
	/**
	 * Getter für die EMail-Addresse.
	 * @return Die EMail-Addresse.
	 */
	public String getEmailAddress() {
	    return emailAddress;
	}
	/**
	 * Getter für den Vornamen.
	 * @return Der Vorname.
	 */
	public String getFirstName() {
	    return firstName;
	}
	/**
	 * Getter für den Nachnamen.
	 * @return Der Nachname.
	 */
	public String getLastName() {
	    return lastName;
	}
};
