// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controller;

import qualityCriteria.QualityCriterion;

/************************************************************/
/**
 * Dieser Controller ist zuständig für das Bearbeiten der Http-Requests, welche
 * durch das Klicken eines Links und nicht eines Buttons versendet werden.
 */
public class AdminPageController extends Controller {

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator Projekte
	 * sieht, neue hinzufügen, sowie existierende löschen kann.
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result projectPage() {
		// TODO
		return null;
	}

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator alle
	 * Projektbetreuer sehen, neue hinzufügen oder bereits existierende
	 * entfernen kann.
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result adviserPage() {
		// TODO
		return null;
	}

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator
	 * Einteilungen berechnen und vorher Parameter einstellen kann. Außerdem
	 * sieht er noch zu berechnende Konfigurationen und kann diese aus der
	 * Berechnungsliste entfernen.
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result allocationPage() {
		// TODO
		return null;
	}

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator die
	 * Ergebnisse der Berechnungen sehen, vergleichen und editieren kann.
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result resultsPage() {
		// TODO
		return null;
	}

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator
	 * Einteilungen, Studentendaten, SPOs, Projekte und CMS-Daten ex- und
	 * importieren kann.
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result exportImportPage() {
		// TODO
		return null;
	}

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator Studenten
	 * manuell hinzufügen oder löschen kann.
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result studentEditPage() {
		// TODO
		return null;
	}

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator die
	 * Semester-Einstellungen vornehmen kann.
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result propertiesPage() {
		// TODO
		return null;
	}

	/**
	 * Diese Methode gibt die Seite zurück, auf der der Administrator ein Projekt editieren kann.
	 * 
	 * @param name Der Name des Projektes (da mitgegeben über die URL, ist der String encoded)
	 * 
	 * @return Die Seite, die als Antwort verschickt wird.
	 */
	public Result projectEditPage(String name) {
		// TODO
		return null;
	}
}
