// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controller;

/************************************************************/
/**
 * 
 */
public class AdminPropertiesController extends Controller {

	/**
	 * 
	 */
	public void addSemester() {
	}

	/**
	 * 
	 */
	public void removeSemester() {
	}

	/**
	 * 
	 */
	public void addSPO() {
	}

	/**
	 * 
	 */
	public void removeSPO() {
	}

	/**
	 * 
	 */
	public void editSemester() {
	}

	/**
	 * 
	 */
	public void addAchievement() {
	}

	/**
	 * 
	 */
	public void removeAchievement() {
	}
};
