// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controller;

/************************************************************/
/**
 * 
 */
public class AdviserPageController extends Controller {

	/**
	 * 
	 */
	public void projectsPage() {
	}

	/**
	 * 
	 */
	public void addProject() {
	}

	/**
	 * 
	 */
	public void removeProject() {
	}

	/**
	 * 
	 */
	public void editProject() {
	}

	/**
	 * 
	 */
	public void joinProject() {
	}

	/**
	 * 
	 */
	public void leaveProject() {
	}

	/**
	 * 
	 */
	public void saveStudentsGrades() {
	}

	/**
	 * 
	 */
	public void accountPage() {
	}

	/**
	 * 
	 */
	public void editAccount() {
	}
};
