// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.controller;

/************************************************************/
/**
 * 
 */
public abstract class EditAllocationCommand {

	/**
	 * 
	 */
	public abstract void execute();

	/**
	 * 
	 */
	public void undo() {
	}
};
