// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controller;

/************************************************************/
/**
 * 
 */
public class IndexPageController {

	/**
	 * 
	 */
	public void indexPage() {
	}

	/**
	 * 
	 */
	public void registerPage() {
	}

	/**
	 * 
	 */
	public void login() {
	}

	/**
	 * 
	 */
	public void register() {
	}

	/**
	 * 
	 */
	public void passwordResetPage() {
	}

	/**
	 * 
	 */
	public void passwordReset() {
	}

	/**
	 * 
	 */
	public void verificationPage() {
	}
};
