// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.controller;

import RootElement.controller.EditAllocationCommand;

/************************************************************/
/**
 * 
 */
public class MoveStudentCommand extends EditAllocationCommand {

	/**
	 * 
	 */
	public void execute() {
	}

	/**
	 * 
	 */
	public void undo() {
	}
};
