// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.Einteilung;

import RootElement.data.AllocationParameter;
import RootElement.data.Project;
import RootElement.data.Student;

/************************************************************/
/**
 * 
 */
public class Configuration {
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EString AllocationName;
	/**
	 * 
	 */
	public Student[] students;
	/**
	 * 
	 */
	public Project[] projects;
	/**
	 * 
	 */
	public AllocationParameter[] parameters;
};
