// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package daten;

import RootElement.Modell.Daten.Semester;

/************************************************************/
/**
 * 
 */
public class GeneralData {
    			/**
    			 * 
    			 */
    			public static Semester currentSemester;
    			/**
    			 * 
    			 */
    			public Semester ;
    			/**
    			 * 
    			 */
    			public static String AdminName;
    			/**
    			 * 
    			 */
    			public static String AdminPassword;
};
