// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package daten;

import RootElement.Modell.Daten.Rating;
import RootElement.Modell.Daten.Semester;
import RootElement.Modell.Daten.Student;

/************************************************************/
/**
 * 
 */
public class LearningGroup {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public Semester;
	/**
	 * 
	 */
	public Semester semester;
	/**
	 * 
	 */
	public Student[] students;
	/**
	 * 
	 */
	public Rating[] ratings;

	/**
	 * 
	 */
	public boolean private;
	
	/**
	 * 
	 * @param name 
	 * @return learningGroup 
	 * @param semester 
	 */
	public static RootElement.Modell.Daten.LearningGroup getLearningGroup(String name, Semester semester) {
	}

	/**
	 * 
	 * @return learningGroups 
	 */
	public static RootElement.Modell.Daten.LearningGroup getLearningGroups() {
	}
};
