// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package benachrichtigung;

import daten.Allocation;
import daten.User;

/************************************************************/
/**
 * 
 */
public abstract class Notifier {

	/**
	 * 
	 * @param allocation 
	 */
	public void notifyAllUsers(Allocation allocation) {
	}

	/**
	 * 
	 * @param allocation 
	 * @param user 
	 */
	public void notifyUser(Allocation allocation, User user) {
	}

	/**
	 * 
	 * @param user 
	 */
	public void sendNewPassword(User user) {
	}
};
