// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

/************************************************************/
/**
 * Diese Klasse stellt einen Parameter für die Einteilungsberechnung dar.
 */
public class AllocationParameter {
	/**
	 * Der Name des Parameters.
	 */
	private String name;
	/**
	 * Die Gewichtung des Parameters.
	 */
	private double value;
	/**
	 * Getter für den Namen des Parameters.
	 * 
	 * @return Der Name des Parameters.
	 */
	public String getName() {
	    return name;
	}
	/**
	 * Getter für den Wert des Parameters.
	 * 
	 * @return Der Wert des Parameters.
	 */
	public double getValue() {
	    return value;
	}
	
	/**
     * Setter für den Namen des Parameters.
     * 
     * @param name Der Name des Parameters.
     */
    public void getName(String name) {
        this.name = name;
    }
    /**
     * Setter für den Wert des Parameters.
     * 
     * @param value Der Wert des Parameters.
     */
    public void getValue(double value) {
        this.value = value;
    }
}
