// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

/************************************************************/
/**
 * Klasse, die die Datenbank initialisiert.
 */
public class PSEServerConfigStartup implements ServerConfigStartup {
	
	/**
	 * Initialisiert die Datenbank.
	 * 
	 * @param serverConfig ein Objekt, welches zur Konfiguration des Servers verwendet wird.
	 */
	public void onStartup(ServerConfig serverConfig) {
		
	}
}
