// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

/************************************************************/
/**
 * Diese Klasse stellt eine Bewertung eines Studierenden oder einerr Lerngruppe für ein Projekt dar.
 */
public class Rating {
	/**
	 * Der Wert der Bewertung.
	 */
	private int rating;
	/**
	 * Das Projekt, dem die Bewertung gilt.
	 */
	private Project project;
	/**
	 * Die Lerngruppe, welche die Bewertung abgegeben hat.
	 */
	private LearningGroup learningGroup;
	/**
	 * Getter für den Wert der Bewertung.
	 * @return Der Wert der Bewertung.
	 */
	public int getRating() {
	    return rating;
	}
	/**
	 * Getter für das Projekt der Bewertung.
	 * @return Das Projekt, das bewertet wird.
	 */
	public Project getProject() {
	    return project;
	}
	/**
	 * Getter für die Lerngruppe.
	 * @return Die Lerngruppe, die bewertet.
	 */
	public LearningGroup getLearningGroup() {
	    return this.learningGroup;
	}
	
	/**
     * Setter für den Wert der Bewertung.
     * @param rating Der Wert der Bewertung.
     */
    public void setRating(int rating) {
        this.rating = rating;
    }
    /**
     * Setter für das Projekt der Bewertung.
     * @param project Das Projekt, das bewertet wird.
     */
    public void setProject(Project project) {
        this.project = project;
    }
    /**
     * Setter für die Lerngruppe.
     * @param learningGroup Die Lerngruppe, die bewertet.
     */
    public void setLearningGroup(LearningGroup learningGroup) {
        this.learningGroup = learningGroup;
    }
}
