// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package data;

import java.util.Date;

/************************************************************/
/**
 * Diese Klasse reprüsentiert ein Semseter.
 */
public class Semester {
	/**
	 * Der Name des Semesters im Format: *******
	 */
	private String name;
	/**
	 * Die für dieses Semseter verfügbaren SPOs
	 */
	private SPO[] spos;
	/**
	 * Eine Beschreibung/Infotext des Semesters.
	 */
	private String infoText;
	/**
	 * Die finale Einteilung der Studierenden auf die Projekte/Teams.
	 */
	private Allocation finalAllocation;
	/**
	 * Der Zeitpunkt ab dem sich Studenten registrieren können.
	 */
	private Date registrationStart;
	/**
	 * Der Zeitpunkt ab dem sich Studenten nicht mehr registrieren können.
	 */
	private Date registrationEnd;
	
	/**
	 * Getter für den Namen des Semesters.
	 * 
	 * @return Der Name des Semesters.
	 */
	public String getName() {
	    return name;
	}
	/**
	 * Getter für die SPOs des Semesters.
	 * 
	 * @return Die verfügbaren SPOs des Semesters.
	 */
	public SPO[] getSpos() {
	    return spos;
	}
	/**
	 * Getter für den Infotext.
	 * 
	 * @return Der Infotext des Semesters.
	 */
	public String getInfoText() {
	    return infoText;
	}
	/**
	 * Getter für die finale Einteilung.
	 * 
	 * @return Die finale Einteilung.
	 */
	public Allocation getFinalAllocation() {
	    return finalAllocation;
	}
	
	/**
     * Setter für den Namen des Semesters.
     * 
     * @param name Der Name des Semesters.
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Setter für die SPOs des Semesters.
     * 
     * @param spos Die verfügbaren SPOs des Semesters.
     */
    public void setSpos(SPO[] spos) {
        this.spos = spos;
    }
    /**
     * Setter für den Infotext.
     * 
     * @param infoText Der Infotext des Semesters.
     */
    public void setInfoText(String infoText) {
        this.infoText = infoText;
    }
    /**
     * Setter für die finale Einteilung.
     * 
     * @param finalAllocation Die finale Einteilung.
     */
    public void setFinalAllocation(Allocation finalAllocation) {
        this.finalAllocation = finalAllocation;
    }
    
	/**
	 * Diese Methode gibt ein spezifisches Semester zurück.
	 * 
	 * @param semesterName Der Name des Semseters.
	 * @return semester Das gesuchte Semester.
	 */
	public static Semester getSemester(String semesterName) {
		//TODO
				return null;
	}

	/**
	 * Diese Methode gibt alles Semseter zurück, die erstellt wurden.
	 * 
	 * @return semesters Alle Semseter.
	 */
	public static Semester getSemesters() {
		//TODO
				return null;
	}

	/**
	 * Diese Methode gibt alles Teams zurück.
	 * 
	 * @return teams Alle existierenden Teams.
	 */
	public Team getTeams() {
		//TODO
				return null;
	}

	/**
	 * Diese Methode gibt alle Betreuer dieses Semesters zurück.
	 * 
	 * @return advisers Alle Betreuer des Semesters.
	 */
	public Adviser getAdvisers() {
		//TODO
				return null;
	}
	
	/**
	 * Setter für den Startzeitpunkt der Registrierung.
	 * 
	 * @param start der Startzeitpunkt.
	 */
	public void setRegistrationStart(Date start) {
		this.registrationStart = start;
	}
	
	/**
	 * Getter für den Startpunkt der Registrierung.
	 * 
	 * @retun den Startzeitpunkt.
	 */
	public Date getRegistrtaionStart() {
		return registrationStart;
	}
	
	/**
	 * Setter für den Endzeitpunkt der Registrierung.
	 * 
	 * @param start der Endzeitpunkt.
	 */
	public void setRegistrationEnd(Date end) {
		this.registrationEnd = end;
	}
	
	/**
	 * Getter für den Endzeitpunkt der Registrierung.
	 * 
	 * @retun den Endzeitpunkt.
	 */
	public Date getRegistrationEnd() {
		return registrationEnd;
	}
}
