// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package qualityCriteria;

/************************************************************/
/**
 * Gütekriterium, das die Anzahl der nicht zugeteilten Studenten berechnet
 */
public class NotAllocatedStudents implements QualityCriterion{
	
	public String calculate(Allocation allocation){
	}
}
