// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.Gütekriterien;

import RootElement.Gütekriterien.QualityCriterion;

/************************************************************/
/**
 * Gütekriterium, das die Anzahl der nicht zugeteilten Studenten berechnet
 */
public class NotAllocatedStudents implements QualityCriterion{
	
	public void calculate(Allocation allocation){
	}
};
