// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package qualityCriteria;

import data.Allocation;

/************************************************************/
/**
 * Gütekriterium, das die Anzahl der zerteilten Lerngruppen berechnet
 */
public class splitLearningGroups implements QualityCriterion {
	
    /**
     * {@inheritDoc}
     */
	@Override
	public String calculate(Allocation allocation) {
		// TODO
		return null;
	}
}
