// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package qualityCriteria;

/************************************************************/
/**
 * Gütekriterium, das die Studentenhappiness berechnet
 */
public class StudentHappiness implements QualityCriterion{
	
	public String calculate(Allocation allocation){
	}
}
