// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package qualityCriteria;

import data.Allocation;

/************************************************************/
/**
 * Gütekriterium, das die Studentenhappiness berechnet
 */
public class StudentHappiness implements QualityCriterion {

	public String calculate(Allocation allocation) {
		// TODO
		return null;
	}
}
