// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package einteilung;

import einteilung.ILPAllocator;

/************************************************************/
/**
 * 
 */
public interface Criterion {

	/**
	 * 
	 * @param weight 
	 * @param allocator 
	 */
	public void useCriteria(int weight, ILPAllocator allocator);

	/**
	 * 
	 * @return  
	 */
	public String getName();
};
