// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package qualityCriteria;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.ServiceLoader;

/************************************************************/
/**
 * Klasse, die alle Gütekriterien lädt.
 */
public class QualityCriteriaLoader {

    /**
     * Utility Klasse sollte nicht instanziiert werden.
     */
    private QualityCriteriaLoader() {
    }

    /**
     * Gibt alle gütekriterien zurück.
     * 
     * @return Liste aller Gütekriterien
     */
    public static List<QualityCriterion> getAllQualityCriteria() {
        ArrayList<QualityCriterion> qc = new ArrayList<>();
        Iterator<QualityCriterion> iter = ServiceLoader
                .load(QualityCriterion.class).iterator();
        while (iter.hasNext()) {
            qc.add(iter.next());
        }
        return qc;
    }
}
