// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package qualityCriteria;

import data.Allocation;
import data.GeneralData;
import data.LearningGroup;
import data.Project;
import data.Student;

/************************************************************/
/**
 * Gütekriterium, das die Anzahl der zerteilten Lerngruppen berechnet
 */
public class splitLearningGroups implements QualityCriterion {

    /**
     * {@inheritDoc}
     */
    @Override
    public String calculate(Allocation allocation) {
        int numberOfSplitLearningGroups = 0;
        for (int i = 0; i < GeneralData.getInstance().getCurrentSemester().getLearningGroups().size(); i++) {
            LearningGroup lg = GeneralData.getInstance().getCurrentSemester().getLearningGroups().get(i);
            Project p1 = lg.getMembers().get(0).getCurrentProject();
            if (!lg.isPrivate() && lg.getMembers().size() > 1) {
                boolean hasBeenDevided = false;
                for (int j = 1; (j < lg.getMembers().size()) && !hasBeenDevided; j++) {
                    Student memberJ = lg.getMembers().get(j);
                    if (memberJ.getCurrentProject() != null && !memberJ.getCurrentProject().equals(p1)) {
                        hasBeenDevided = true;
                    }
                }
                if (hasBeenDevided) {
                    numberOfSplitLearningGroups++;
                }
            }
        }
        return String.valueOf(numberOfSplitLearningGroups);
    }

    @Override
    public String getName() {
        return "Getrennte Lerngruppen";
    }
}
