// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ImportExport;

import RootElement.ImportExport.CMSConflict;
import RootElement.data.Allocation;
import RootElement.data.Semester;

/************************************************************/
/**
 * 
 */
public class Importer {

	/**
	 * 
	 * @param file 
	 * @param semester 
	 */
	public void importAllocation(EcorePrimitiveTypes.EString file, Semester semester) {
	}

	/**
	 * 
	 * @param file 
	 * @param allocation 
	 */
	public void exportAllocation(EcorePrimitiveTypes.EString file, Allocation allocation) {
	}

	/**
	 * 
	 * @param file 
	 * @return  
	 */
	public CMSConflict importCMSData(EcorePrimitiveTypes.EString file) {
	}

	/**
	 * 
	 * @param file 
	 */
	public void exportCMSData(EcorePrimitiveTypes.EString file) {
	}
};
