// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement;

import controller.IndexPageController;
import daten.Student;

/************************************************************/
/**
 * looks whether student already exists
 */
public class register {
	/**
	 * 
	 */
	public IndexPageController indexPageController;
	/**
	 * 
	 */
	public static Student Student;
	/**
	 * 
	 */
	public Student student;
};
