// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package allocation;

/************************************************************/
/**
 * Das Kriterium sorgt dafür Studierende die mehr als die die zur Teilname am PSE
 * benötigten Teilleistungen bestanden haben bevorzugt werden.
 */
public class CriterionAdditionalPerfomances implements Criterion {
	private String name;

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void useCriteria(int weight, GurobiAllocator allocator) {
		// TODO Auto-generated method stub
		
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return null;
	}
}
