// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package allocation;

/************************************************************/
/**
 * Das Kriterium sorgt dafür das Lerngruppen eher zusammenbleiben.
 */
public class CriterionLearningGroup implements Criterion {
	private String name;
};