// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package allocation;

/************************************************************/
/**
 * Das Kriterium sorgt dafür das Teams möglichst die gewünschte Teamgröße haben.
 */
public class CriterionPreferredTeamSize implements Criterion {
	private String name;

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void useCriteria(int weight, GurobiAllocator allocator) {
		// TODO Auto-generated method stub
		
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		// TODO Auto-generated method stub
		return null;
	}
}