// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package allocation;

/************************************************************/
/**
 * Das Kriterium sorgt dafür das möglichst kein Team aus einer Lerngrupe sowie
einem einzelnen Studierenden besteht.
 */
public class CriterionNoSingularStudent implements Criterion {
	private String name;
};