// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.Einteilung;

import RootElement.Einteilung.Criterion;

/************************************************************/
/**
 * Das Kriterium sorgt dafür das möglichst viele Studierende Teams zugeteilt
werden.
 */
public class CriterionAllocated implements Criterion {
	private String name;
};