// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.Benachrichtigung;

import RootElement.data.Allocation;
import RootElement.data.Student;
import RootElement.data.User;

/************************************************************/
/**
 * 
 */
public class Notifier {

	/**
	 * 
	 * @param allocation 
	 */
	public void notifyAllUsers(Allocation allocation) {
	}

	/**
	 * 
	 * @param allocation 
	 * @param user 
	 */
	public void notifyUser(Allocation allocation, User user) {
	}

	/**
	 * 
	 * @param user 
	 */
	public void sendNewPassword(User user) {
	}

	/**
	 * 
	 * @param student 
	 */
	public void sendVerificationMail(Student student) {
	}

	/**
	 * 
	 * @param student 
	 * @param code 
	 */
	public void verify(Student student, EcorePrimitiveTypes.EString code) {
	}
};
