// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.Gütekriterien;

import RootElement.Gütekriterien.QualityCriterion;

/************************************************************/
/**
 * 
 */
public class QualityCriteriaLoader {

	/**
	 * 
	 * @return  
	 */
	public static QualityCriterion getAllQualityCriteria() {
	}
};
