// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.Gütekriterien;

import RootElement.Gütekriterien.QualityCriterion;

/************************************************************/
/**
 * Gütekriterium, das die Studentenhappiness berechnet
 */
public class StudentHappiness implements QualityCriterion{
	
	public void calculate(Allocation allocation){
	}
};
