// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package gütekriterien;

import gütekriterien.QualityCriteria;

/************************************************************/
/**
 * 
 */
public class NotAllocatedStudents extends QualityCriteria {
};
