// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package controllers;

import java.util.List;

import com.google.inject.Inject;

import data.Adviser;
import data.Allocation;
import data.ElipseModel;
import data.GeneralData;
import data.Grade;
import data.Project;
import data.Semester;
import data.Student;
import data.Team;
import play.data.DynamicForm;
import play.data.FormFactory;
import play.mvc.Controller;
import play.mvc.Result;
import security.BlowfishPasswordEncoder;
import security.UserManagement;
import views.AdviserMenu;
import views.Menu;

/************************************************************/
/**
 * Dieser Controller ist für das Bearbeiten der Http-Requests zuständig, welche
 * im Betreuerbereich aufkommen.
 */
public class AdviserPageController extends Controller {

    private static final String INTERNAL_ERROR = "error.internalError";

    @Inject
    FormFactory                 formFactory;

    /**
     * Diese Methode gibt die Seite zurück, auf der der Betreuer Projekte sieht,
     * Projekte hinzufügen, editieren oder entfernen kann. Editieren und
     * Entfernen eines Projektes ist beschränkt auf Betreuer, welche dem Projekt
     * beigetreten sind.
     * 
     * @param id
     *            Die ID des Projekts
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result projectsPage(int id) {
        Menu menu = new AdviserMenu(ctx(), ctx().request().path());
        // kein Element ausgewählt
        if (id == -1) {
            if (GeneralData.loadInstance().getCurrentSemester().getProjects()
                    .size() == 0) {
                play.twirl.api.Html content = views.html.adviserNoProject
                        .render();
                return ok(views.html.adviser.render(menu, content));
            } else {
                id = GeneralData.loadInstance().getCurrentSemester()
                        .getProjects().get(0).getId();
            }
        }

        Project project = ElipseModel.getById(Project.class, id);

        UserManagement user = new UserManagement();
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        play.twirl.api.Html content;
        if (adviser.getProjects().contains(project)) {
            // Ist der Betreuer schon Betreuer des Projektes?
            Allocation finalAlloc = GeneralData.loadInstance()
                    .getCurrentSemester().getFinalAllocation();
            if (finalAlloc != null) { // Lade Seite, auf der der Betreuer seine
                                      // eingeteilten Teams sieht
                content = views.html.adviserAllocationInfo
                        .render(finalAlloc.getTeamsByProject(project));
            } else { // Lade Seite zum editieren der Projekteinstellungen
                content = views.html.projectEdit.render(project, true,
                        Adviser.getAdvisers());
            }
        } else { // Lade Seite zum Beitreten zum Projekt, wenn er noch nicht
                 // Betreuer des Projektes ist
            content = views.html.adviserProjectJoin.render(project);
        }
        // true bedeutet das der aufrufende adviser ist
        return ok(views.html.adviser.render(menu, content));
    }

    /**
     * Diese Methode fügt ein neues Projekt in das System ein, fügt diesen
     * betreuer als Adviser ein und leitet den Betreuer zurück auf die Seite zum
     * Editieren des Projektes.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result addProject() {
        UserManagement user = new UserManagement();
        int projID = -1;
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        Project project = new Project(
                "new Project" + adviser.getFirstName() + adviser.getLastName(),
                adviser);
        project.save();
        projID = project.getId();
        Semester semester = GeneralData.loadInstance().getCurrentSemester();
        semester.doTransaction(() -> {
            semester.addProject(project);
        });
        return redirect(
                controllers.routes.AdviserPageController.projectsPage(projID));
    }

    /**
     * Diese Methode löscht ein Projekt und alle dazugehörenden Daten aus dem
     * System und leitet den Betreuer auf die Seite zum Editieren und Hinzufügen
     * von Projekten. Nur Betreuer welche dem Projekt beigetreten sind können
     * dieses editieren.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result removeProject() {
        UserManagement user = new UserManagement();
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        DynamicForm form = formFactory.form().bindFromRequest();
        if (form.data().isEmpty()) {
            return badRequest(ctx().messages().at(INTERNAL_ERROR));
        }
        int id = Integer.parseInt(form.get("id"));
        Project project = ElipseModel.getById(Project.class, id);
        if (adviser.getProjects().contains(project)) {
            // TODO Warnung vorm löschen
            project.delete();
        }
        return redirect(controllers.routes.AdviserPageController
                .projectsPage(GeneralData.loadInstance().getCurrentSemester()
                        .getProjects().get(0).getId()));
    }

    /**
     * Diese Methode editiert ein bereits vorhandenes Projekt. Die zu
     * editierenden Daten übermittelt der Betreuer über ein Formular, welches er
     * zum Editieren abschickt. Nur Betreuer welche dem Projekt beigetreten sind
     * können dieses editieren. Anschließend wird der Betreuer auf die Seite zum
     * Hinzufügen und Editieren von Projekten weitergeleitet.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result editProject() {
        UserManagement user = new UserManagement();
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        // alle daten werden aus formular ausgelesen
        DynamicForm form = formFactory.form().bindFromRequest();
        if (form.data().isEmpty()) {
            return badRequest(ctx().messages().at(INTERNAL_ERROR));
        }
        String projName = form.get("name");
        String url = form.get("url");
        String institute = form.get("institute");
        String description = form.get("description");
        String numberOfTeamsString = form.get("teamCount");
        String minSizeString = form.get("minSize");
        String maxSizeString = form.get("maxSize");
        String idString = form.get("id");
        int id = Integer.parseInt(idString);
        int numberOfTeams;
        int minSize;
        int maxSize;
        Project project = ElipseModel.getById(Project.class, id);
        boolean isAdviser = adviser.getProjects().contains(project);
        if (!isAdviser) {
            flash("error", ctx().messages().at(INTERNAL_ERROR));
            return redirect(
                    controllers.routes.AdviserPageController.projectsPage(id));
        }
        try {
            numberOfTeams = Integer.parseInt(numberOfTeamsString);
            minSize = Integer.parseInt(minSizeString);
            maxSize = Integer.parseInt(maxSizeString);
        } catch (NumberFormatException e) {
            flash("error", ctx().messages().at("error.wrongInput"));
            return redirect(
                    controllers.routes.AdviserPageController.projectsPage(id));
        }

        project.doTransaction(() -> {
            project.setInstitute(institute);
            project.setMaxTeamSize(maxSize);
            project.setMinTeamSize(minSize);
            project.setName(projName);
            project.setNumberOfTeams(numberOfTeams);
            project.setProjectInfo(description);
            project.setProjectURL(url);
        });

        return redirect(controllers.routes.AdviserPageController
                .projectsPage(project.getId()));
    }

    /**
     * Diese Methode fügt einen Betreuer zu einem bereits existierenden Projekt
     * hinzu, sodass dieser auch die Möglichkeit besitzt das Projekt zu
     * editieren oder zu löschen und nach der Veröffentlichung einer Einteilung
     * auch Teams und deren Mitglieder sieht. Nach dem Beitreten wird der
     * Betreuer auf die Seite zum Hinzufügen und Editieren von Projekten
     * weitergeleitet.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result joinProject() {
        UserManagement user = new UserManagement();
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        DynamicForm form = formFactory.form().bindFromRequest();
        if (form.data().isEmpty()) {
            return badRequest(ctx().messages().at(INTERNAL_ERROR));
        }
        int id = Integer.parseInt(form.get("id"));
        Project project = ElipseModel.getById(Project.class, id);
        if (!adviser.getProjects().contains(project)) {
            project.doTransaction(() -> {
                project.addAdviser(adviser);
            });
        } else {
            flash("error", ctx().messages().at(INTERNAL_ERROR));
        }
        return redirect(controllers.routes.AdviserPageController
                .projectsPage(project.getId()));
    }

    /**
     * Diese Methode entfernt einen Betreuer aus einem existierenden Projekt,
     * sodass dieser nicht mehr das Projekt editieren oder löschen kann.
     * Anschließend wird der Betreuer auf die Seite zum Hinzufügen und Editieren
     * von Projekten weitergeleitet.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result leaveProject() {
        UserManagement user = new UserManagement();
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        DynamicForm form = formFactory.form().bindFromRequest();
        if (form.data().isEmpty()) {
            return badRequest(ctx().messages().at(INTERNAL_ERROR));
        }
        int id = Integer.parseInt(form.get("id"));
        Project project = ElipseModel.getById(Project.class, id);
        if (adviser.getProjects().contains(project)) {
            project.doTransaction(() -> {
                project.removeAdviser(adviser);
            });
        } else {
            flash("error", ctx().messages().at(INTERNAL_ERROR));
        }
        return redirect(controllers.routes.AdviserPageController
                .projectsPage(project.getId()));
    }

    /**
     * Diese Methode speichert alle von einem Betreuer in ein Formular
     * eingegebenen Noten eines Teams, sodass diese vom Administrator in das CMS
     * importiert werden können. Anschließend wird der Betreuer auf die
     * Projektseite des jeweiligen Projektes weitergeleitet.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result saveStudentsGrades() {
        UserManagement user = new UserManagement();
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        // alle daten werden aus formular ausgelesen
        DynamicForm form = formFactory.form().bindFromRequest();
        if (form.data().isEmpty()) {
            return badRequest(ctx().messages().at(INTERNAL_ERROR));
        }
        String idString = form.get("id");
        int id = Integer.parseInt(idString);
        Project project = ElipseModel.getById(Project.class, id);
        boolean isAdviser = adviser.getProjects().contains(project);
        if (!isAdviser) {
            flash("error", ctx().messages().at(INTERNAL_ERROR));
            return redirect(
                    controllers.routes.AdviserPageController.projectsPage(id));
        }
        // Dies nur ausführen, falls Betreuer wirklich zum Projekt gehört
        Allocation finalAlloc = GeneralData.loadInstance().getCurrentSemester()
                .getFinalAllocation();
        if (finalAlloc == null) {
            flash("error", ctx().messages().at(INTERNAL_ERROR));
        }
        List<Team> teams = finalAlloc.getTeamsByProject(project);
        for (Team team : teams) {
            for (Student student : team.getMembers()) {
                int pseGrade;
                int tseGrade;
                try {
                    pseGrade = Integer
                            .parseInt(form.get(student.getId() + "-pseGrade"));
                    tseGrade = Integer
                            .parseInt(form.get(student.getId() + "-tseGrade"));
                } catch (NumberFormatException e) {
                    return redirect(controllers.routes.AdviserPageController
                            .projectsPage(id));
                }
                student.doTransaction(() -> {
                    student.setGradePSE(Grade.getGradeByNumber(pseGrade));
                    student.setGradeTSE(Grade.getGradeByNumber(tseGrade));
                });
            }
        }
        return redirect(
                controllers.routes.AdviserPageController.projectsPage(id));
    }

    /**
     * Diese Methode gibt die Seite zurück, auf der der Betreuer seine
     * Benutzerdaten wie E-Mail-Adresse und Passwort ändern kann.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result accountPage() {
        play.twirl.api.Html content = views.html.adviserAccount.render();
        Menu menu = new AdviserMenu(ctx(), ctx().request().path());
        return ok(views.html.adviser.render(menu, content));
    }

    /**
     * Diese Methode editiert die Daten des Betreuers, welche er auf der
     * Account-Seite geändert hat.
     * 
     * @return die Seite, die als Antwort verschickt wird.
     */
    public Result editAccount() {
        UserManagement user = new UserManagement();
        Adviser adviser = (Adviser) user.getUserProfile(ctx());
        DynamicForm form = formFactory.form().bindFromRequest();
        if (form.data().isEmpty()) {
            return badRequest(ctx().messages().at(INTERNAL_ERROR));
        }

        if (form.get("passwordChange") != null) {
            System.out.println("passwordChange1");
            String oldpw = form.get("oldPassword");
            String pw = form.get("newPassword");
            String pwrepeat = form.get("newPasswordRepeat");

            boolean matches = new BlowfishPasswordEncoder().matches(oldpw,
                    adviser.getPassword());

            if (!pw.equals(pwrepeat) || !matches) {
                flash("error",
                        ctx().messages().at("adviser.account.error.passwords"));
                return redirect(
                        controllers.routes.AdviserPageController.accountPage());
            }
            String pwEnc = new BlowfishPasswordEncoder().encode(pw);
            adviser.doTransaction(() -> {
                adviser.setPassword(pwEnc);
            });
        }
        if (form.get("emailChange") != null) {
            String email = form.get("newEmail");
            adviser.doTransaction(() -> {
                adviser.setEmailAddress(email);
            });
            // TODO hier verifikation
        }
        return redirect(controllers.routes.AdviserPageController.accountPage());
    }
}
