// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package importExport;

import daten.Achievement;
import daten.Student;

/************************************************************/
/**
 * 
 */
public class CMSConflict {
	/**
	 * 
	 */
	public Student student;
	/**
	 * 
	 */
	public Achievement achievement;
	/**
	 * 
	 */
	public EcorePrimitiveTypes.EBoolean newCompleted;
};
