// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ImportExport;

import data.Achievement;
import data.Student;

/************************************************************/
/**
 * 
 */
public class CMSConflict {
	/**
	 * 
	 */
	public Student student;
	/**
	 * 
	 */
	public Achievement achievement;
	/**
	 * 
	 */
	public EcorePrimitiveTypes.EBoolean newCompleted;
};
