// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package importExport;

import data.Allocation;
import data.Semester;

/************************************************************/
/**
 * 
 */
public class Importer {

	/**
	 * 
	 * @param file 
	 * @param semester 
	 */
	public void importAllocation(String file, Semester semester) {
	}

	/**
	 * 
	 * @param file 
	 * @param allocation 
	 */
	public void exportAllocation(String file, Allocation allocation) {
	}

	/**
	 * 
	 * @param file 
	 * @return  
	 */
	public void importCMSData(String file) {
	}

	/**
	 * 
	 * @param file 
	 */
	public void exportCMSData(String file) {
	}
}
